SELECT TO_TIMESTAMP(t/1000) AS t, field, value FROM
(
(SELECT t, CAST(high_volt_disocnnect AS text) AS value, 'high_volt_disocnnect' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(charging_limit_voltage AS text) AS value, 'charging_limit_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(over_voltage_reconnect AS text) AS value, 'over_voltage_reconnect' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(equalization_voltage AS text) AS value, 'equalization_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(boost_voltage AS text) AS value, 'boost_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(float_voltage AS text) AS value, 'float_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(boost_reconnect_voltage AS text) AS value, 'boost_reconnect_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(low_voltage_reconnect AS text) AS value, 'low_voltage_reconnect' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(under_voltage_recover AS text) AS value, 'under_voltage_recover' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(under_voltage_warning AS text) AS value, 'under_voltage_warning' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(low_voltage_disconnect AS text) AS value, 'low_voltage_disconnect' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(discharging_limit_voltage AS text) AS value, 'discharging_limit_voltage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(battery_temperature_warning_upper_limit AS text) AS value, 'battery_temperature_warning_upper_limit' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(battery_temperature_warning_lower_limit AS text) AS value, 'battery_temperature_warning_lower_limit' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(controller_inner_temperature_upper_limit AS text) AS value, 'controller_inner_temperature_upper_limit' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(controller_inner_temperature_upper_limit_recover AS text) AS value, 'controller_inner_temperature_upper_limit_recover' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(day_time_threshold_volt AS text) AS value, 'day_time_threshold_volt' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(light_signal_startup_night_delay_time AS text) AS value, 'light_signal_startup_night_delay_time' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(light_time_threshold_volt AS text) AS value, 'light_time_threshold_volt' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(light_signal_close_day_delay_time AS text) AS value, 'light_signal_close_day_delay_time' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(load_controlling_modes AS text) AS value, 'load_controlling_modes' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(working_time_length_1 AS text) AS value, 'working_time_length_1' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(working_time_length_2 AS text) AS value, 'working_time_length_2' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(turn_on_timing_1 AS text) AS value, 'turn_on_timing_1' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(turn_off_timing_1 AS text) AS value, 'turn_off_timing_1' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(turn_on_timing_2 AS text) AS value, 'turn_on_timing_2' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(turn_off_timing_2 AS text) AS value, 'turn_off_timing_2' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(backlight_time AS text) AS value, 'backlight_time' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(night_length AS text) AS value, 'night_length' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(batt_rated_voltage_code AS text) AS value, 'batt_rated_voltage_code' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(manual_default_load_onoff AS text) AS value, 'manual_default_load_onoff' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(equalize_duration AS text) AS value, 'equalize_duration' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(boost_duration AS text) AS value, 'boost_duration' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(discharging_percentage AS text) AS value, 'discharging_percentage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(charging_percentage AS text) AS value, 'charging_percentage' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(charging_management_modes AS text) AS value, 'charging_management_modes' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(charging_device_onoff AS text) AS value, 'charging_device_onoff' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1)
UNION (SELECT t, CAST(enable_load_test_mode AS text) AS value, 'enable_load_test_mode' AS field FROM epever_config_name ORDER BY t DESC LIMIT 1
)
)
ORDER BY field

